---
kind: pipeline
name: default

steps:
  - name: build & run tests
    image: r.mills.io/prologic/golang-alpine-ffmpeg:latest
    volumes:
      - name: gomodcache
        path: /go/pkg/mod/cache
    privileged: true
    environment:
      GOPROXY: https://goproxy.mills.io
    commands:
      - make deps
      - make build
      - make test

  - name: build & publish docker image
    image: r.mills.io/drone_plugins/docker
    settings:
      debug: true
      registry: r.mills.io
      repo: r.mills.io/prologic/yarn
      tags: latest
      build_args:
        - VERSION=${DRONE_TAG}
        - COMMIT=${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: notify
    image: plugins/webhook
    settings:
      urls:
        - https://msgbus.mills.io/ci.mills.io
    when:
      status:
        - success
        - failure

volumes:
  - name: gomodcache
    host:
      path: /var/lib/cache/go
