---
kind: pipeline
name: default

steps:
  - name: build-and-test
    image: r.mills.io/prologic/golang-alpine-ffmpeg:latest
    commands:
      - make deps
      - make build
      - make test

  - name: build-dev-site
    image: plugins/kaniko
    settings:
      registry: r.mills.io
      repo: r.mills.io/prologic/dev.twtxt.net
      tags: latest
      dockerfile: docs/Dockerfile
      context: docs
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

  - name: notify-irc
    image: plugins/webhook
    settings:
      urls:
        - https://msgbus.mills.io/ci.mills.io
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - tag
    - push
    - pull_request
