---
builds:
  - id: twt
    binary: twt
    main: ./cmd/twt
    flags: -tags "static_build"
    ldflags: >-
      -w
      -X git.mills.io/yarnsocial/yarn.Version={{.Version}}
      -X git.mills.io/yarnsocial/yarn.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - amd64

signs:
  - artifacts: checksum
brews:
  -
    tap:
      owner: prologic
      name: homebrew-twtxt
    homepage: "https://github.io/jointwt/twtxt"
    description: |
      📕 twtxt is a Self-Hosted, Twitter™-like Decentralised microBlogging
      platform. No ads, no tracking, your content, your data!
release:
  github:
    owner: prologic
    name: twtxt
  draft: true
