---
builds:
  - id: yarnc
    binary: yarnc
    main: ./cmd/yarnc
    flags: -tags "static_build"
    ldflags: >-
      -w
      -X git.mills.io/yarnsocial/yarn.Version={{.Version}}
      -X git.mills.io/yarnsocial/yarn.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
  - id: yarnd
    binary: yarnd
    main: ./cmd/yarnd
    flags: -tags "static_build"
    ldflags: >-
      -w
      -X git.mills.io/yarnsocial/yarn.Version={{.Version}}
      -X git.mills.io/yarnsocial/yarn.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
signs:
  - artifacts: checksum
release:
  gitea:
    owner: yarnsocial
    name: yarn
  draft: true
gitea_urls:
  api: https://git.mills.io/api/v1/
