---
version: "3.8"

services:
  yarnd:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000/tcp"
    volumes:
      - ./data:/src/data
      - ./internal:/src/internal
