---
version: "3.8"

services:
  traefik:
    image: traefik:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik:/data
    command:
      - --accesslog
      - --api
      - --certificatesResolvers.acme.acme.dnschallenge=true
      - --certificatesResolvers.acme.acme.dnschallenge.provider=cloudflare
      - --certificatesResolvers.acme.acme.email=youraddress@email.com
      - --certificatesResolvers.acme.acme.storage=/data/acme.json
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certresolver=acme
      - --entrypoints.https.http.tls.domains[0].main=*.mypoddomain.com
      - --entrypoints.https.http.tls.domains[0].sans=mypoddomain.com
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --providers.docker.swarmmode=true
      - --providers.docker.watch=true
      - --providers.file.directory=/data/rules
      - --providers.file.watch=true
    environment:
      - CLOUDFLARE_EMAIL=yourcloudflare@email.com
      - CLOUDFLARE_API_KEY=your-cloudflare-api-key
    deploy:
      endpoint_mode: dnsrr
      replicas: 1

networks:
  traefik:
    external: true

volumes:
  traefik:
    driver: local
