[CustomLinkAddSubmit]
hash = "sha1-2cf006b19170d54873467ced16c631aff563e7f9"
other = "Add Link"

[CustomLinkAddTitle]
hash = "sha1-a6f299e58aaaca46f83e05de13d75bca9e9c11f7"
other = "Link Title"

[CustomLinkAddURL]
hash = "sha1-08738f6eef34333c426e9fb2c58d5a55999d681f"
other = "Link URL"

[CustomLinkSummary]
hash = "sha1-baf0d50958c28b349b7256a571a2ef3d39e46a98"
other = "Here you can add a new link to the User Links section of your profile"

[CustomLinkTitle]
hash = "sha1-db86eac66fd08d6cdb48fd70674e176d2d44bdb1"
other = "Add Custom Link"

[ErrorAddLink]
hash = "sha1-2e3c4ce83c2859f0449f42a50d0fc8787ca9c948"
other = "Error adding link"

[ErrorRemoveLink]
hash = "sha1-a0d1b318fdb682f356e2e5cd9598415ad7035091"
other = "Error removing link"

[LinkVerifyApprove]
hash = "sha1-dda6ac27b9d3b234a68e8b2c412e90ab5a03a4e1"
other = "Verify"

[LinkVerifyCancel]
hash = "sha1-77dfd2135f4db726c47299bb55be26f7f4525a46"
other = "Cancel"

[LinkVerifyMessage]
hash = "sha1-c9fb1362d9b51a3752351b0b53e9579df6bcda6c"
other = "You are about to visit a link that is external to <strong>{{ .InstanceName }}</strong>. Please verify the URL before continuing."

[LinkVerifyNoURL]
hash = "sha1-7615c8d9ba516af03858134992e383d2b0e20bf8"
other = "No external URL provided."

[LinkVerifyTitle]
hash = "sha1-a8748e2f6fb8a27630517bf258a863c8f0ac579f"
other = "Verify External Link"

[ManagePodPermittedImageDomains]
hash = "sha1-06153c0e0f405f78995607b80e0e85ec9c82396a"
other = "Permitted Domains"

[MsgAddLinkSuccess]
hash = "sha1-6a0a25a5ae7f58e26527c3aafff4d46dfa6d5669"
other = "Successfully added link"

[MsgRemoveLinkSuccess]
hash = "sha1-c50929ee55b955fed357699e2c89c2decc45fda6"
other = "Successfully removed link"

[ProfileInfo]
hash = "sha1-9486a1afca121ed3afba4b9aaef1d564acff2b5a"
other = "User Info"

[ProfileLinks]
hash = "sha1-96348083f320cb5fc4ea1736274b4072f6277689"
other = "User Links"

[ProfileNoDescription]
hash = "sha1-fe3f10ae47cf6f826ac900b3c510bfe6745352da"
other = "No description provided."

[ProfileToolTitle]
hash = "sha1-503b2943687edb378c72d1ed3b4bd9508399a80c"
other = "Mute / Report User"

[SettingsTwtCompact]
hash = "sha1-fd2dd04bba8ecc916a7824bc4ed1994c729ab28b"
other = "Compact View"

[SettingsTwtCustomColorHelp]
hash = "sha1-a6ca11b7dc2a0edd2960f9e7175c95a7b4442596"
other = "Type in either the literal name of the colour or hex code you want to use, i.e. orange or #ff8c00 <em>(make sure to include the # for the hex code)</em><br>A list of interesting colors can be found here: <a href='https://www.colorhexa.com/color-names'>https://www.colorhexa.com/color-names</a>"

[SettingsTwtCustomColorPrimary]
hash = "sha1-db1f3745e1f8b469d71cfc5b09c3a2a48d835d45"
other = "Custom Primary Color"

[SettingsTwtCustomColorReset]
hash = "sha1-95edea4f499af09af280d6b9fc08ba0f5bbc0371"
other = "Leave blank to clear"

[SettingsTwtCustomColorSecondary]
hash = "sha1-3c057063ffcb6a49552b96621e628cc7d853628c"
other = "Custom Hover/Select Color"

[SettingsTwtLinkVerification]
hash = "sha1-14d432aea790bc01e64fadd2a974a0343477bf66"
other = "Link Verification"

[SettingsTwtReadmore]
hash = "sha1-8cc343cc97d1c6b44fb48a756acc33ed7ddd2151"
other = "Collapse Content"

[SettingsTwtReadmoreHelp]
hash = "sha1-92f330412f3d5b5797e11408f6bd6a6c2e5cac31"
other = "Adds a 'Read More' section to longer content.<br><strong>Javascript is required</strong>"

[SettingsTwtStripTrackingParam]
hash = "sha1-5d6c1723e5f5208285cf52693a564bb1c66946a9"
other = "Strip Link Parameters"

[SettingsTwtStripTrackingParamHelp]
hash = "sha1-78d44b0d6bdac2fe2c02e6764bb83e3754191b62"
other = "This removes third party tracking from posted URLs<br>Query parameters will be removed from URLs such as; utm_, sc_, fb_"

[SettingsTwtTitle]
hash = "sha1-1596bf6271ab348f04a599625045a31278048c86"
other = "Twt Preferences"

[TwtReadLess]
hash = "sha1-b64a80b45c6536d87213c530639e606e6b3b2368"
other = "⤊ Read Less"

[TwtReadMore]
hash = "sha1-3cd30b88aa928be52c30cdba5c0499429ba65c83"
other = "⤋ Read More"
