[ManageFeedDeleteSummary]
hash = "sha1-fe87884b05a6d6092b978938bcdba1dcbe2027af"
other = "Your feed will be deleted permanently!"

[ManageFeedDeleteTitle]
hash = "sha1-cdf081498909a5f915c8a8e2b9740d02c1f5c8e9"
other = "Delete Feed"

[MsgDeleteFeedSuccess]
hash = "sha1-9075948e33bebcc514e6618482fa388e6dd2deb5"
other = "Successfully deleted feed"
