[InstanceNameInfo]
hash = "sha1-bb97ffe973568947d8903b91c044bd17dee96723"
other = "About the <b>{{ .InstanceName }}</b> Yarn.social pod."

[InstanceTitle]
hash = "sha1-914e2403bda42fb7ddb728a9337741354d4ab938"
other = "Pod Information"

[ProfileDoesNotFollowYou]
hash = "sha1-7a19de4a06edde3c1acac1919d17b8a26c8b6bc9"
other = "does not follow you... (<small>your replies may go unnoticed</small>)"

[ProfileMuteUser]
hash = "sha1-30772b5b5cde04fdc46e43460d1b7096cb8a2601"
other = "You are free to Unfollow or Mute this user or feed.&#10;Muting will also remove that user/feed's content from your view.&#10;You will no longer see content from that user/feed anywhere."

[ProfileReportUser]
hash = "sha1-8ea1aab3d7221d789f3a6b80ef950d80b6ccb65b"
other = "If this user/feed is violating this Pod's ({{ .InstanceName }})&#10;community guidelines as set out in the Abuse Policy,&#10;please report them immediately!"

[SettingsInfoMissingTagline]
hash = "sha1-fe3f10ae47cf6f826ac900b3c510bfe6745352da"
other = "No description provided."

[SettingsInfoUserInfo]
hash = "sha1-9486a1afca121ed3afba4b9aaef1d564acff2b5a"
other = "User Info"

[SettingsInfoUserLinks]
hash = "sha1-96348083f320cb5fc4ea1736274b4072f6277689"
other = "User Links"
